### ISSUE TITLE
Could not generate a proxy class for class com.uber.infer.task.PrepareForInfer.

### ISSUE THREAD

**Issue by vanniktech** [uber-common/infer-plugin#12]
I'm getting this error when applying it onto an Android project when using version `0.7.0` of this plugin and `0.8.1` of infer.

You could also check out the PR over here https://github.com/artem-zinnatullin/qualitymatters/pull/178 to get a sample where the plugin breaks.

**Comment by tonycosentini** [comment]
Hey @vanniktech,

Thanks for the repro steps - I'll take a look.

**Comment by vanniktech** [comment]
According to the stacktrace there seems to be a packaging error / missing dependencies:

> Caused by: java.lang.NoClassDefFoundError: com/amazonaws/util/json/JSONArray
	at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:67)
	at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:51)
	at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:31)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:260)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:216)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:95)
	... 102 more
Caused by: java.lang.ClassNotFoundException: com.amazonaws.util.json.JSONArray

**Comment by clonetwin26** [comment]
Cut a new release under infer plugin 0.7.1 removing this class

**Comment by tonycosentini** [comment]
This should be fixed in v0.7.1 now - do let us know if it's still an issue.

Thanks for the helpful bug report!

**Comment by vanniktech** [comment]
This is fixed with `0.7.1`. Thank you
